[package]
name = "unzip-com-take-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intercom = "0.4.0"
flate2 = "1.0.26"
libc = "0.2.147"


[lib]
crate-type = ["cdylib"]
